#!/usr/bin/env python3
"""to_diagram_design.py — export a design system as a diagram-design profile.

diagram-design (github.com/cathrynlavery/diagram-design) draws the diagram types this
repo does not (swimlane, org chart, Venn, funnel, treemap, heatmap, Gantt, Sankey,
fishbone, Wardley, kanban, journey, charts, …). It reads its look from a *profile*: a
style guide with a `### Semantic roles` table and a `## Typography` table, stored in
`~/.diagram-design/profiles/<slug>.md` and selected per project by a `.diagram-design`
file containing `profile: <slug>`. This script maps our tokens onto those roles so a
delegated diagram lands in the same theme.

Usage:
    python3 to_diagram_design.py [--design-system coral]            # print the profile
    python3 to_diagram_design.py --design-system coral --write [--marker DIR]
        # write ~/.diagram-design/profiles/ds-coral.md (+ DIR/.diagram-design) — ask first
    python3 to_diagram_design.py --self-test
"""

from __future__ import annotations

import argparse
import datetime as _dt
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import design_tokens as dt  # noqa: E402

SLUG = re.compile(r"^[a-z0-9][a-z0-9-]{0,63}$")


def mix(a: str, b: str, k: float) -> str:
    pa = [int(a[i : i + 2], 16) for i in (1, 3, 5)]
    pb = [int(b[i : i + 2], 16) for i in (1, 3, 5)]
    return "#" + "".join(f"{round(x + (y - x) * k):02X}" for x, y in zip(pa, pb, strict=True))


def roles(t: dict) -> dict[str, str]:
    """Our tokens → diagram-design's semantic roles. Its `accent` is a stroke and text
    colour on paper, so it takes the theme's first strong colour that reads there (3:1);
    a light highlighter such as Studio's yellow becomes the accent *tint* instead."""
    c = t["color"]
    paper = c["canvas"]

    def hued(h: str) -> bool:
        r, g, b = (int(h[i : i + 2], 16) for i in (1, 3, 5))
        return max(r, g, b) - min(r, g, b) > 60

    # the theme's own emphasis: its hued badge colour (coral red), else the highlight
    # itself when it reads as a stroke (midnight periwinkle), else ink (studio, paper-line)
    strong = next(
        (
            x
            for x, ok in ((c["badge"], hued(c["badge"])), (c["accent"], True), (c["ink"], True))
            if ok and dt.contrast(x, paper) >= 3.0
        ),
        c["ink"],
    )
    light_hl = dt.contrast(c["ink"], c["accent"]) >= 4.5 and dt.luminance(c["accent"]) > 0.4
    return {
        "paper": paper,
        "paper-2": c["group"] if c["group"].upper() != paper.upper() else c["tile"],
        "ink": c["ink"],
        "ink-strong": c["accent-ink"]
        if dt.contrast(c["accent-ink"], c["accent"]) >= 4.5
        else c["ink"],
        "muted": c["muted"],
        "soft": c["lede"] if dt.contrast(c["lede"], paper) >= 4.5 else c["muted"],
        "rule": c["subtle"],
        "rule-solid": c["border"],
        "accent": strong,
        "accent-tint": c["accent"] if light_hl else mix(paper, strong, 0.1),
        "link": c["series-2"],
    }


PURPOSE = {
    "paper": "Page background, default node fill",
    "paper-2": "Diagram container bg, secondary fill",
    "ink": "Primary text, primary stroke",
    "ink-strong": "High-contrast text on accent fills",
    "muted": "Secondary text, default arrow stroke",
    "soft": "Sublabels, boundary labels",
    "rule": "Hairline borders",
    "rule-solid": "Stronger borders, baselines",
    "accent": "Focal / 1-2 max per diagram",
    "accent-tint": "Fill for accent-bordered boxes",
    "link": "HTTP/API calls, external arrows",
}


def profile(t: dict, slug: str, today: str | None = None) -> str:
    today = today or _dt.date.today().isoformat()
    r = roles(t)
    ty = t["type"]
    c = t["color"]
    family = lambda stack: stack.split(",")[0].strip().strip("'\"")  # noqa: E731
    sans, mono, serif = family(ty["sans"]), family(ty["mono"]), family(ty["serif"])
    rows = "\n".join(f"| `{k}` | {PURPOSE[k]} | `{v}` | `{v}` |" for k, v in r.items())
    series = "\n".join(
        f"| `series-{i}` | `{c[f'series-{i}']}` | `{c[f'series-{i}']}` | Non-focal series |"
        for i in range(1, 5)
    )
    return f"""<!-- diagram-design-profile
name: diagram-skills {t["name"]}
slug: {slug}
source-url: none
created: {today}
updated: {today}
notes: Generated by diagram-skills to_diagram_design.py from the {t["name"]} design system
-->
# Style Guide

Generated from the diagram-skills `{t["name"]}` design system, so diagrams drawn here match
the ones its compilers draw. One mode only: the light and dark columns are the same theme.

## Tokens

### Semantic roles

| Role | Purpose | Default (light) | Default (dark) |
|---|---|---|---|
{rows}

### Series palette (multi-series chart types only)

| Token | Light | Dark | Notes |
|---|---|---|---|
{series}
| `series-5` | `{c["muted"]}` | `{c["muted"]}` | Non-focal series |

---

## Typography

| Role | Family | Size | Weight | Usage |
|---|---|---|---|---|
| `title` | {sans} | 1.75rem | {ty["title-weight"]} | Page H1 |
| `node-name` | {sans} | 12px | {max(600, ty["label-weight"])} | Human-readable labels |
| `sublabel` | {mono} | 9px | 400 | Port, protocol, URL, field type |
| `eyebrow` | {mono} | 7-8px | 500, tracked 0.18em, uppercase | Type tags, axis labels |
| `arrow-label` | {mono} | 8px | 400, tracked 0.06em | Arrow annotations |
| `callout` | {serif} *italic* | 14px | 400 | Editorial asides only |

### Inline figures

Diagrams sit inline in an article: draw no page title, kicker or eyebrow above the
figure (the article heading and caption carry them), keep outer padding even and
modest, and keep the legend only when a colour or line style needs explaining.

### Shape

Corner radius {t["shape"]["radius"]}px on nodes ({t["shape"]["radius-small"]}px on small tags);
strokes {t["shape"]["stroke"]}px ({t["shape"]["stroke-strong"]}px for emphasis); arrowheads
`{t["shape"]["arrow"]}`; node borders `{t["shape"]["card-border"]}`.

### Font stack

Use these stacks as written and load no web fonts (the diagram must render offline):
sans `{ty["sans"]}`; mono `{ty["mono"]}`; serif `{ty["serif"]}`.
"""


def self_test() -> int:
    for name in ("studio", "coral", "paper-line", "midnight"):
        t = dt.load(name)
        p = profile(t, f"ds-{name}", "2026-01-01")
        r = roles(t)
        assert (
            p.startswith("<!-- diagram-design-profile")
            and "### Semantic roles" in p
            and "## Typography" in p
        )
        assert (
            all(f"| `{k}` |" in p for k in PURPOSE)
            and "Corner radius" in p
            and "Inline figures" in p
        ), name
        assert dt.contrast(r["accent"], r["paper"]) >= 3.0, (name, r["accent"])
        assert (
            dt.contrast(r["ink"], r["paper"]) >= 4.5 and dt.contrast(r["muted"], r["paper"]) >= 4.5
        ), name
    st = dt.load("studio")["color"]
    assert roles(dt.load("studio"))["accent-tint"] == st["accent"]  # the yellow card stays the tint
    assert roles(dt.load("studio"))["accent"] == st["ink"]  # and the focal stroke is ink
    print("OK: self-test passed")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--design-system", default=None, help="theme name or design-system.md path")
    ap.add_argument("--slug", default=None, help="profile slug (default: ds-<theme name>)")
    ap.add_argument(
        "--write", action="store_true", help="write ~/.diagram-design/profiles/<slug>.md"
    )
    ap.add_argument(
        "--marker", type=Path, help="also write DIR/.diagram-design selecting the profile"
    )
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    try:
        t = dt.load(a.design_system)
    except dt.TokenError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    slug = a.slug or f"ds-{re.sub(r'[^a-z0-9-]', '-', t['name'].lower())}"[:64]
    if not SLUG.match(slug) or slug == "default":
        print(
            f"ERROR: invalid profile slug {slug!r} (lowercase letters, digits, hyphens; not 'default')",
            file=sys.stderr,
        )
        return 1
    text = profile(t, slug)
    if not a.write:
        sys.stdout.write(text)
        return 0
    dest = Path.home() / ".diagram-design" / "profiles" / f"{slug}.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8")
    print(f"OK: wrote {dest}")
    if a.marker:
        (a.marker / ".diagram-design").write_text(f"profile: {slug}\n", encoding="utf-8")
        print(f"OK: wrote {a.marker / '.diagram-design'} (profile: {slug})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
